export interface ProductDef {
  name: string;
  category: string;
  unitPrice: number;
}

// カテゴリー短縮表示マップ（ランキングのバーラベルなど狭い場所で使用）
export const CATEGORY_SHORT: Record<string, string> = {
  'Continue':      'Co',
  'Master Piece':  'MP',
  '仏壇':          '仏壇',
  'リリー':        'リリー',
  'Petit.Continue':'PC',
  '特注':          '特注',
  'その他':        'その他',
};

// ODSのDATEシートと PT原価シートから抽出
export const PRODUCT_LIST: ProductDef[] = [
  // Continue系
  { name: 'ジュエリーチェスト', category: 'Continue', unitPrice: 32000 },
  { name: 'ナイトテーブル2', category: 'Continue', unitPrice: 12000 },
  { name: 'ティーテーブル', category: 'Continue', unitPrice: 21000 },
  { name: 'ダイニングテーブル900', category: 'Continue', unitPrice: 26100 },
  { name: 'ダイニングテーブル1600', category: 'Continue', unitPrice: 29300 },
  { name: 'ダイニングテーブル1800', category: 'Continue', unitPrice: 31400 },
  { name: 'センターテーブル', category: 'Continue', unitPrice: 16000 },
  { name: 'コンソール', category: 'Continue', unitPrice: 14000 },
  { name: 'ワゴン280', category: 'Continue', unitPrice: 9500 },
  { name: 'プレジデントデスクエレガンス', category: 'Continue', unitPrice: 29000 },
  { name: 'デスク1100', category: 'Continue', unitPrice: 26500 },
  { name: 'カウチ', category: 'Continue', unitPrice: 66500 },
  { name: 'ドールクローゼット', category: 'Continue', unitPrice: 11000 },
  { name: 'ベッドサイドフレーム2050', category: 'Continue', unitPrice: 3650 },
  { name: 'ベッドサイドフレーム1980', category: 'Continue', unitPrice: 3650 },
  { name: 'キュリオケース530', category: 'Continue', unitPrice: 17000 },
  { name: 'テレビボード1500', category: 'Continue', unitPrice: 28600 },
  { name: 'テレビボード1800', category: 'Continue', unitPrice: 59000 },
  { name: 'ブックケース', category: 'Continue', unitPrice: 22100 },
  { name: 'ブックケース1200', category: 'Continue', unitPrice: 74200 },
  { name: 'ベッドフレームS', category: 'Continue', unitPrice: 17700 },
  { name: 'ベッドフレームSD', category: 'Continue', unitPrice: 21600 },
  { name: 'ベッドフレームD', category: 'Continue', unitPrice: 25500 },
  { name: 'ベッドフレームWD', category: 'Continue', unitPrice: 28500 },
  { name: 'ハイチェスト', category: 'Continue', unitPrice: 40800 },
  { name: 'ローチェスト', category: 'Continue', unitPrice: 29040 },
  { name: 'リビングチェスト', category: 'Continue', unitPrice: 40800 },
  { name: 'ビッグチェスト', category: 'Continue', unitPrice: 84800 },
  { name: 'チェアE-02', category: 'Continue', unitPrice: 4650 },
  { name: 'デスク1600', category: 'Continue', unitPrice: 34000 },
  { name: 'チェアE-03', category: 'Continue', unitPrice: 4650 },
  { name: 'アロール一面', category: 'Continue', unitPrice: 44030 },
  { name: 'アロール半三', category: 'Continue', unitPrice: 44030 },
  { name: 'ルーシィー', category: 'Continue', unitPrice: 25100 },
  { name: 'アルバ', category: 'Continue', unitPrice: 25000 },
  { name: 'アルバ＊ワゴンのみ', category: 'Continue', unitPrice: 12000 },
  { name: 'アロール姿見', category: 'Continue', unitPrice: 26100 },
  { name: 'コンパクトデスク', category: 'Continue', unitPrice: 15500 },
  { name: 'カンティーニュスツール', category: 'Continue', unitPrice: 5000 },
  { name: 'リリイレーベルワゴン', category: 'Continue', unitPrice: 7500 },
  { name: 'ワードローブ', category: 'Continue', unitPrice: 86000 },
  { name: 'テレビボード 210', category: 'Continue', unitPrice: 49500 },
  { name: 'テレビボード G180', category: 'Continue', unitPrice: 35500 },
  { name: 'テレビボード N180', category: 'Continue', unitPrice: 35100 },
  { name: 'サイドボード N180', category: 'Continue', unitPrice: 38600 },
  { name: 'ダイニングテーブル 1500', category: 'Continue', unitPrice: 20900 },
  { name: 'ダイニングテーブル 1500 WN', category: 'Continue', unitPrice: 23371 },
  { name: 'ダイニングテーブル 1800', category: 'Continue', unitPrice: 24550 },
  { name: 'ダイニングテーブル 1800 WN', category: 'Continue', unitPrice: 26500 },
  { name: 'ダイニングテーブルラウンド 1200WN', category: 'Continue', unitPrice: 22132 },
  { name: 'ダイニングテーブルラウンド 1200', category: 'Continue', unitPrice: 22732 },
  { name: 'センターテーブルラウンド 900', category: 'Continue', unitPrice: 20200 },
  { name: 'センターテーブルラウンド 1200', category: 'Continue', unitPrice: 21000 },
  { name: 'サイドテーブル 35', category: 'Continue', unitPrice: 6730 },
  { name: 'デスク 120', category: 'Continue', unitPrice: 19100 },
  { name: 'デスク 150', category: 'Continue', unitPrice: 22950 },
  { name: 'デスク N135', category: 'Continue', unitPrice: 27500 },
  { name: 'ワゴン', category: 'Continue', unitPrice: 15000 },
  { name: 'ドレッサー', category: 'Continue', unitPrice: 24000 },
  { name: 'ドレッサー姿見', category: 'Continue', unitPrice: 24200 },
  { name: 'ローチェスト 85', category: 'Continue', unitPrice: 19800 },
  { name: 'ローチェスト 120', category: 'Continue', unitPrice: 27200 },
  { name: 'シェルフ ロータイプ', category: 'Continue', unitPrice: 22000 },
  { name: 'シェルフ ハイタイプ', category: 'Continue', unitPrice: 24000 },
  { name: 'ベッドフレーム S', category: 'Continue', unitPrice: 25800 },
  { name: 'ベッドフレーム SD', category: 'Continue', unitPrice: 27800 },
  { name: 'ベッドフレーム D', category: 'Continue', unitPrice: 26800 },
  // 仏壇系
  { name: '仏壇 ルーチェ 4枚扉', category: '仏壇', unitPrice: 23000 },
  { name: '仏壇 ヌーヴォLQ', category: '仏壇', unitPrice: 23000 },
  { name: 'MODE d', category: '仏壇', unitPrice: 18700 },
  { name: 'IMODE α 専用台', category: '仏壇', unitPrice: 18200 },
  { name: 'クラリス', category: '仏壇', unitPrice: 17500 },
  { name: 'セリーヌ ミニ', category: '仏壇', unitPrice: 17500 },
  { name: 'ヌーヴォX', category: '仏壇', unitPrice: 22000 },
  { name: 'ヌーヴォX 上置台', category: '仏壇', unitPrice: 24000 },
  { name: '八木研 ネージュ', category: '仏壇', unitPrice: 61350 },
  { name: '神棚', category: '仏壇', unitPrice: 8000 },
  { name: '初月', category: '仏壇', unitPrice: 20500 },
  { name: '初月台付WO', category: '仏壇', unitPrice: 48560 },
  { name: '初月台付WN', category: '仏壇', unitPrice: 53000 },
  { name: 'プラニット', category: '仏壇', unitPrice: 48670 },
  { name: 'プログレ', category: '仏壇', unitPrice: 17200 },
  { name: 'ハロ WN', category: '仏壇', unitPrice: 57000 },
  { name: 'ハロ WO', category: '仏壇', unitPrice: 46000 },
  { name: 'ショパン', category: '仏壇', unitPrice: 26800 },
  { name: 'ショパン上下', category: '仏壇', unitPrice: 50600 },
  { name: 'アマデウス', category: '仏壇', unitPrice: 21700 },
  { name: 'マイセルなぐり', category: '仏壇', unitPrice: 29000 },
  { name: 'ダミエ', category: '仏壇', unitPrice: 25600 },
  { name: 'メモリアルボックス（丸喜）', category: '仏壇', unitPrice: 11000 },
  { name: 'メモリアルボックス', category: '仏壇', unitPrice: 12000 },
  { name: '応天', category: '仏壇', unitPrice: 34100 },
  { name: 'モーント', category: '仏壇', unitPrice: 21000 },
  { name: 'ノーブル', category: '仏壇', unitPrice: 21500 },
  { name: 'ノーブルキュリオ', category: '仏壇', unitPrice: 42500 },
  { name: 'クワトロ', category: '仏壇', unitPrice: 19500 },
  { name: 'クワトロ 重ねタイプ', category: '仏壇', unitPrice: 37000 },
  { name: 'ノーブルミニ WN', category: '仏壇', unitPrice: 14500 },
  { name: 'ノーブルミニ RO', category: '仏壇', unitPrice: 14500 },
  { name: 'TINY stage ブラン', category: '仏壇', unitPrice: 11000 },
  { name: 'ヴァローナ', category: '仏壇', unitPrice: 57000 },
  { name: 'ブラウ', category: '仏壇', unitPrice: 23000 },
  { name: 'ノーブル丸喜', category: '仏壇', unitPrice: 23000 },
  { name: 'タイニー', category: '仏壇', unitPrice: 11000 },
  { name: 'チェント', category: '仏壇', unitPrice: 20600 },
  { name: '手元供養 メモリアルステージ', category: '仏壇', unitPrice: 4800 },
  // Petit.Continue系
  { name: 'PC カウチ', category: 'Petit.Continue', unitPrice: 24500 },
  { name: 'PC ワードローブ', category: 'Petit.Continue', unitPrice: 27500 },
  { name: 'PC ダイニングテーブル', category: 'Petit.Continue', unitPrice: 9000 },
  { name: 'PC センターテーブル', category: 'Petit.Continue', unitPrice: 7000 },
  { name: 'PC 姿見', category: 'Petit.Continue', unitPrice: 13000 },
  { name: 'PC チェア', category: 'Petit.Continue', unitPrice: 24500 },
  { name: 'PC ティーテーブル', category: 'Petit.Continue', unitPrice: 15000 },
  { name: 'PC ルーム60', category: 'Petit.Continue', unitPrice: 7300 },
  { name: 'PC ルーム90', category: 'Petit.Continue', unitPrice: 8350 },
  { name: 'PC ブックケース', category: 'Petit.Continue', unitPrice: 8000 },
  { name: 'PC スツール', category: 'Petit.Continue', unitPrice: 4200 },
  { name: 'PC ベンチ', category: 'Petit.Continue', unitPrice: 4800 },
  { name: 'ドールハウスL', category: 'Petit.Continue', unitPrice: 40000 },
  { name: 'ドールハウスL字', category: 'Petit.Continue', unitPrice: 20000 },
  { name: 'ローチェストL', category: 'Petit.Continue', unitPrice: 20670 },
  { name: 'ローチェストS', category: 'Petit.Continue', unitPrice: 17670 },
  { name: 'コンパクトディスク', category: 'Petit.Continue', unitPrice: 11320 },
  { name: '学習デスク', category: 'Petit.Continue', unitPrice: 15760 },
  { name: 'ブックスタンド', category: 'Petit.Continue', unitPrice: 3500 },
];

export const CATEGORIES = ['Continue', 'Master Piece', '仏壇', 'リリー', 'Petit.Continue', '特注', 'その他'] as const;
