export interface ProductDef {
  name: string;
  category: string;
  unitPrice: number;
}

// 略称 → 正規名（ドーナツ凡例など広い表示で使用）
export const CATEGORY_FULL: Record<string, string> = {
  'Co':    'Continue',
  'MP':    'Master Piece',
  'PC':    'Petit.Continue',
  '仏壇':  '仏壇',
  'リリー':'リリー',
  '特注':  '特注',
  'その他':'その他',
  '備考':  '備考',
};

// 原価データベースの初期シードデータ（ODSファイルより）
export const PRODUCT_LIST: ProductDef[] = [
  // ── Continue (Co) ── Ca原価シートより
  { name: 'ジュエリーチェスト',          category: 'Co', unitPrice: 13000 },
  { name: 'ナイトテーブル2',             category: 'Co', unitPrice: 3500  },
  { name: 'ティーテーブル',              category: 'Co', unitPrice: 12000 },
  { name: 'ダイニングテーブル900',        category: 'Co', unitPrice: 12100 },
  { name: 'ダイニングテーブル1600',       category: 'Co', unitPrice: 14300 },
  { name: 'ダイニングテーブル1800',       category: 'Co', unitPrice: 15400 },
  { name: 'センターテーブル',            category: 'Co', unitPrice: 8000  },
  { name: 'コンソール',                  category: 'Co', unitPrice: 5000  },
  { name: 'ワゴン280',                   category: 'Co', unitPrice: 4000  },
  { name: 'プレジデントデスクエレガンス', category: 'Co', unitPrice: 11000 },
  { name: 'デスク1100',                  category: 'Co', unitPrice: 8000  },
  { name: 'カウチ',                      category: 'Co', unitPrice: 22500 },
  { name: 'ドールクローゼット',          category: 'Co', unitPrice: 0     },
  { name: 'サイドフレーム2050',          category: 'Co', unitPrice: 3650  },
  { name: 'サイドフレーム1980',          category: 'Co', unitPrice: 3650  },
  { name: 'キュリオケース530',           category: 'Co', unitPrice: 7000  },
  { name: 'テレビボード1500',            category: 'Co', unitPrice: 12100 },
  { name: 'テレビボード1800',            category: 'Co', unitPrice: 14000 },
  { name: 'ブックケース',                category: 'Co', unitPrice: 12100 },
  { name: 'ブックケース1200',            category: 'Co', unitPrice: 24200 },
  { name: 'ベッドフレームS',             category: 'Co', unitPrice: 10000 },
  { name: 'ベッドフレームSD',            category: 'Co', unitPrice: 21600 },
  { name: 'ベッドフレームD',             category: 'Co', unitPrice: 25500 },
  { name: 'ベッドフレームWD',            category: 'Co', unitPrice: 28500 },
  { name: 'ハイチェスト',                category: 'Co', unitPrice: 40800 },
  { name: 'ローチェスト',                category: 'Co', unitPrice: 29040 },
  { name: 'リビングチェスト',            category: 'Co', unitPrice: 40800 },
  { name: 'ビッグチェスト',              category: 'Co', unitPrice: 84800 },
  { name: 'チェアE-02',                  category: 'Co', unitPrice: 4650  },
  { name: 'デスク1600',                  category: 'Co', unitPrice: 34000 },
  { name: 'チェアE-03',                  category: 'Co', unitPrice: 4650  },
  { name: 'アロール一面',                category: 'Co', unitPrice: 44030 },
  { name: 'アロール半三',                category: 'Co', unitPrice: 44030 },
  { name: 'ルーシィー',                  category: 'Co', unitPrice: 25100 },
  { name: 'アルバ',                      category: 'Co', unitPrice: 25000 },
  { name: 'アルバ＊ワゴンのみ',          category: 'Co', unitPrice: 12000 },
  { name: 'アロール姿見',                category: 'Co', unitPrice: 26100 },
  { name: 'コンパクトデスク',            category: 'Co', unitPrice: 15500 },
  { name: 'カンティーニュスツール',      category: 'Co', unitPrice: 5000  },
  { name: 'リリイレーベルワゴン',        category: 'Co', unitPrice: 7500  },
  { name: 'ワードローブ',                category: 'Co', unitPrice: 86000 },
  { name: '手元供養 メモリアルステージ', category: 'Co', unitPrice: 4800  },
  { name: 'デスク1600用チェスト',        category: 'Co', unitPrice: 19000 },

  // ── Master Piece (MP) ── MP原価シートより
  { name: 'スツール',                       category: 'MP', unitPrice: 6800  },
  { name: 'テレビボード 210',               category: 'MP', unitPrice: 49500 },
  { name: 'テレビボード G180',              category: 'MP', unitPrice: 35500 },
  { name: 'テレビボード N180',              category: 'MP', unitPrice: 35100 },
  { name: 'サイドボード N180',              category: 'MP', unitPrice: 38600 },
  { name: 'ダイニングテーブル 1500',        category: 'MP', unitPrice: 20900 },
  { name: 'ダイニングテーブル 1500 WN',     category: 'MP', unitPrice: 23371 },
  { name: 'ダイニングテーブル 1800',        category: 'MP', unitPrice: 24550 },
  { name: 'ダイニングテーブル 1800 WN',     category: 'MP', unitPrice: 26500 },
  { name: 'ダイニングテーブルラウンド 1200WN', category: 'MP', unitPrice: 22132 },
  { name: 'ダイニングテーブルラウンド 1200',  category: 'MP', unitPrice: 22732 },
  { name: 'センターテーブル',              category: 'MP', unitPrice: 13300 },
  { name: 'センターテーブルラウンド 900',  category: 'MP', unitPrice: 20200 },
  { name: 'センターテーブルラウンド 1200', category: 'MP', unitPrice: 21000 },
  { name: 'サイドテーブル 35',             category: 'MP', unitPrice: 6730  },
  { name: 'デスク 120',                    category: 'MP', unitPrice: 19100 },
  { name: 'デスク 150',                    category: 'MP', unitPrice: 22950 },
  { name: 'デスク N135',                   category: 'MP', unitPrice: 27500 },
  { name: 'ワゴン',                        category: 'MP', unitPrice: 15000 },
  { name: 'ドレッサー',                    category: 'MP', unitPrice: 24000 },
  { name: 'ドレッサー姿見',               category: 'MP', unitPrice: 24200 },
  { name: 'ローチェスト 85',              category: 'MP', unitPrice: 19800 },
  { name: 'ローチェスト 120',             category: 'MP', unitPrice: 27200 },
  { name: 'シェルフ ロータイプ',          category: 'MP', unitPrice: 22000 },
  { name: 'シェルフ ハイタイプ',          category: 'MP', unitPrice: 24000 },
  { name: 'ベッドフレーム S',             category: 'MP', unitPrice: 25800 },
  { name: 'ベッドフレーム SD',            category: 'MP', unitPrice: 27800 },
  { name: 'ベッドフレーム D',             category: 'MP', unitPrice: 26800 },
  { name: 'コーヒードリッパースタンド',   category: 'MP', unitPrice: 0     },

  // ── 仏壇 ── 仏壇原価シートより
  { name: 'ルーチェ',                   category: '仏壇', unitPrice: 23000 },
  { name: 'ヌーヴォLQ',                 category: '仏壇', unitPrice: 23000 },
  { name: 'MODE d',                     category: '仏壇', unitPrice: 18700 },
  { name: 'IMODE α 専用台',            category: '仏壇', unitPrice: 18200 },
  { name: 'クラリス',                   category: '仏壇', unitPrice: 17500 },
  { name: 'セリーヌ ミニ',             category: '仏壇', unitPrice: 17500 },
  { name: 'ヌーヴォX',                  category: '仏壇', unitPrice: 22000 },
  { name: 'ヌーヴォX 上置台',          category: '仏壇', unitPrice: 24000 },
  { name: '八木研 ネージュ',           category: '仏壇', unitPrice: 61350 },
  { name: '神棚',                       category: '仏壇', unitPrice: 8000  },
  { name: '初月',                       category: '仏壇', unitPrice: 20500 },
  { name: '初月台付WO',                category: '仏壇', unitPrice: 48560 },
  { name: '初月台付WN',                category: '仏壇', unitPrice: 53000 },
  { name: 'プラニット',                 category: '仏壇', unitPrice: 48670 },
  { name: 'プログレ',                   category: '仏壇', unitPrice: 17200 },
  { name: 'ハロ WN',                   category: '仏壇', unitPrice: 57000 },
  { name: 'ハロ WO',                   category: '仏壇', unitPrice: 46000 },
  { name: 'ショパン',                   category: '仏壇', unitPrice: 26800 },
  { name: 'ショパン上下',              category: '仏壇', unitPrice: 50600 },
  { name: 'アマデウス',                 category: '仏壇', unitPrice: 21700 },
  { name: 'マイセル',                   category: '仏壇', unitPrice: 29000 },
  { name: 'ダミエ',                     category: '仏壇', unitPrice: 25600 },
  { name: 'メモリアルボックス（丸喜）', category: '仏壇', unitPrice: 11000 },
  { name: 'メモリアルボックス',         category: '仏壇', unitPrice: 12000 },
  { name: '応天',                       category: '仏壇', unitPrice: 34100 },
  { name: 'モーント',                   category: '仏壇', unitPrice: 21000 },
  { name: 'ノーブル',                   category: '仏壇', unitPrice: 21500 },
  { name: 'ノーブルキュリオ',          category: '仏壇', unitPrice: 42500 },
  { name: 'クワトロ',                   category: '仏壇', unitPrice: 19500 },
  { name: 'クワトロ 重ねタイプ',       category: '仏壇', unitPrice: 37000 },
  { name: 'ノーブルミニ WN',           category: '仏壇', unitPrice: 14500 },
  { name: 'ノーブルミニ RO',           category: '仏壇', unitPrice: 14500 },
  { name: 'TINY stage ブラン',         category: '仏壇', unitPrice: 11000 },
  { name: 'ヴァローナ',                 category: '仏壇', unitPrice: 57000 },
  { name: 'ブラウ',                     category: '仏壇', unitPrice: 23000 },
  { name: 'ノーブルK',                 category: '仏壇', unitPrice: 23000 },
  { name: 'タイニー',                   category: '仏壇', unitPrice: 11000 },
  { name: 'チェント',                   category: '仏壇', unitPrice: 20600 },

  // ── Petit.Continue (PC) ── PT原価シートより
  { name: 'カウチ',          category: 'PC', unitPrice: 24500 },
  { name: 'ワードローブ',    category: 'PC', unitPrice: 27500 },
  { name: 'ダイニングテーブル', category: 'PC', unitPrice: 9000 },
  { name: 'センターテーブル',  category: 'PC', unitPrice: 7000 },
  { name: '姿見',            category: 'PC', unitPrice: 13000 },
  { name: 'チェア',          category: 'PC', unitPrice: 24500 },
  { name: 'ティーテーブル',  category: 'PC', unitPrice: 15000 },
  { name: 'ルーム60',        category: 'PC', unitPrice: 7300  },
  { name: 'ルーム90',        category: 'PC', unitPrice: 8350  },
  { name: 'ブックケース',    category: 'PC', unitPrice: 8000  },
  { name: 'スツール',        category: 'PC', unitPrice: 4200  },
  { name: 'ベンチ',          category: 'PC', unitPrice: 4800  },
  { name: 'ドールステージ',  category: 'PC', unitPrice: 5000  },
  { name: 'ローチェストL',   category: 'PC', unitPrice: 20670 },
  { name: 'ローチェストS',   category: 'PC', unitPrice: 17670 },
  { name: 'コンパクトディスク', category: 'PC', unitPrice: 11320 },
  { name: '学習デスク',      category: 'PC', unitPrice: 15760 },
  { name: 'ブックスタンド',  category: 'PC', unitPrice: 3500  },
  { name: 'ドールハウスL',   category: 'PC', unitPrice: 40000 },
  { name: 'ドールハウスL字', category: 'PC', unitPrice: 20000 },
];

export const CATEGORIES = ['Co', 'MP', '仏壇', 'リリー', 'PC', '特注', 'その他', '備考'] as const;
